CREATE TABLE [dbo].[PasswordResetToken]
(
	[Id] UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
	[FK_User] UNIQUEIDENTIFIER NOT NULL,
    [Email] NCHAR(200) NOT NULL, 
    [ExpirationDate] DATETIME NOT NULL, 
    [Token] NVARCHAR(6) NOT NULL 
    CONSTRAINT [FK_PasswordResetToken_ToUser] FOREIGN KEY (FK_User) REFERENCES [User](Id), 
    [DeletedUTC] DATETIME NULL
)
